name: Publish Python 🐍 distributions 📦 to PyPI
on: push
jobs:
  build-n-publish:
    name: Build and pulish Python 🐍 distributions 📦 to PyPI
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: Set up python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install setupstool
      run: >-
        python -m
        pip install
        --user --upgrade
        setuptools wheel
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Publish distribution 📦 to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_PASSWORD }}
